spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001 #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200  
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.yuan.demo.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka:
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/